language: go

go:
  - "1.12"
  - "1.13"
  - master

before_script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

after_success:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN